// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/CommentData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:28:38 GMT 2024
 */
package org.jinstagram.entity.comments;






import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.FromTagData;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CommentData_ESTest extends CommentData_ESTest_scaffolding {
    
    
    
    

    
    
    
    @Test
    void testToString() {
        FromTagData fromTagData = new FromTagData("John Doe", "12345");
        CommentData commentData = new CommentData(fromTagData, "2023-10-26T10:00:00", "67890", "This is a comment.");

        String expected = "CommentData [commentFrom=FromTagData{name='John Doe', id='12345'}, createdTime=2023-10-26T10:00:00, id=67890, text=This is a comment.]";
        assertEquals(expected, commentData.toString());
    }
}
