// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;
import org.junit.Test;
import java.util.concurrent.ConcurrentHashMap;
import static org.junit.Assert.assertNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    @Test
    public void testDeregister() {
        // Create an instance of JsonReaderCodeGenerator
        JsonReaderCodeGenerator generator = new JsonReaderCodeGenerator(null, null);

        // Define a class to use for testing
        class TestClass { }

        // Register a JsonReaderInvoker for TestClass
        generator.registerReader(TestClass.class);

        // Assert that a JsonReaderInvoker is registered for TestClass
        assertNull(generator.JSON_READER_INVOKERS.get(TestClass.class));

        // Deregister the JsonReaderInvoker for TestClass
        generator.deregister(TestClass.class);

        // Assert that no JsonReaderInvoker is registered for TestClass
        assertNull(generator.JSON_READER_INVOKERS.get(TestClass.class));
    }
}
