// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/ObjectArray_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {
    @Test
    public void testGet() {
        ObjectArray objectArray = new ObjectArray();
        objectArray.ensureExplicitCapacity(10);
        objectArray.add("TestObject");

        assertEquals("TestObject", objectArray.get(0));

        try {
            objectArray.get(10);
            fail("Expected IndexOutOfBoundsException");
        } catch (IndexOutOfBoundsException e) {
            assertEquals("Index: 10, Size: 1", e.getMessage());
        }
    }
}
