// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/ObjectArray_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.ObjectArray;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {
    @Test
    public void testAdd() {
        ObjectArray objectArray = new ObjectArray();
        Object element = new Object();

        // Add an element to the array
        boolean result = objectArray.add(element);

        // Assert that the addition was successful
        assertTrue(result);

        // Assert that the size of the array is now 1
        assertEquals(1, objectArray.size());

        // Assert that the element was added to the end of the array
        assertEquals(element, objectArray.get(0));
    }
}
