// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.lang.reflect.Field;
import java.lang.reflect;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetAnnotation() {
        // Define a test annotation
        @interface TestAnnotation extends Annotation {
        }

        // Define a test class with a method and field annotated with the test annotation
        class TestClass {
            @TestAnnotation
            public void testMethod() {
            }

            @TestAnnotation
            private Field testField;
        }

        try {
            // Get the test method and field
            Method testMethod = TestClass.class.getMethod("testMethod");
            Field testField = TestClass.class.getDeclaredField("testField");

            // Test retrieving the annotation from the method
            TestAnnotation methodAnnotation = Reflections.getAnnotation(testMethod, null, TestAnnotation.class);
            assert methodAnnotation != null;

            // Test retrieving the annotation from the field
            TestAnnotation fieldAnnotation = Reflections.getAnnotation(null, testField, TestAnnotation.class);
            assert fieldAnnotation != null;
       
        } catch (NoSuchMethodException | NoSuchFieldException e) {
            e.printStackTrace();
        }
    }
}
