// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.reflect.Method;
import java.lang.reflect.Field;
import java.lang
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetFirstGenericParameterType() throws Exception {
        // Create a mock Method object
        Method mockMethod = Reflections.class.getDeclaredMethod("getFirstGenericParameterType", Method.class);
        mockMethod.setAccessible(true);

        // Test with a method that has generic parameter types
        Method methodWithGenericTypes = Reflections.class.getDeclaredMethod("classPresent", String.class);
        Class<?> firstGenericType = (Class<?>) mockMethod.invoke(null, methodWithGenericTypes);
        assertNotNull(firstGenericType);

        // Test with a method that does not have generic parameter types
        Method methodWithoutGenericTypes = Reflections.class.getDeclaredMethod("getField", Class.class, String.class);
        firstGenericType = (Class<?>) mockMethod.invoke(null, methodWithoutGenericTypes);
        assertNull(firstGenericType);
    }
}
