// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testHasAnnotation() throws Exception {
        // Create a mock method and field
        Method mockMethod = Reflections.class.getDeclaredMethod("hasAnnotation", Method.class, Field.class, Class.class);
        Field mockField = Reflections.class.getDeclaredField("hasAnnotation");

        // Create a mock annotation class
        Class<? extends Annotation> mockAnnotationClass = mockMethod.getParameterTypes()[2].asSubclass(Annotation.class);

        // Invoke the method with mock objects
        boolean result = (boolean) mockMethod.invoke(null, mockMethod, mockField, mockAnnotationClass);

        // Assert the result
        org.junit.Assert.assertTrue(result);
    }
}
