// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/TypeImpl_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:15:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TypeImpl_ESTest extends TypeImpl_ESTest_scaffolding {
    @Test
    public void testGetIterableImpl() {
        // Test with List.class
        TypeImpl typeImpl = TypeImpl.getIterableImpl(List.class);
        assertEquals(List.class, typeImpl.getInfClass());
        assertEquals(ArrayList.class, typeImpl.getImplClass());

        // Test with Collection.class
        typeImpl = TypeImpl.getIterableImpl(Collection.class);
        assertEquals(Collection.class, typeImpl.getInfClass());
        assertEquals(ArrayList.class, typeImpl.getImplClass());

        // Test with Iterable.class
        typeImpl = TypeImpl.getIterableImpl(Iterable.class);
        assertEquals(Iterable.class, typeImpl.getInfClass());
        assertEquals(ArrayList.class, typeImpl.getImplClass());

        // Test with abstract class
        try {
            typeImpl = TypeImpl.getIterableImpl(Object.class);
            fail("Expected RuntimeException for abstract class");
        } catch (RuntimeException e) {
            assertEquals("Cannot find appropriate implementation of collection type: java.lang.Object", e.getMessage());
        }

        // Test with interface
        try {
            typeImpl = TypeImpl.getIterableImpl(Iterable.class);
            fail("Expected RuntimeException for interface");
        } catch (RuntimeException e) {
            assertEquals("Cannot find appropriate implementation of collection type: java.lang.Iterable", e.getMessage());
        }
    }
}
