// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;
import org.junit.Test;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    @Test
    public void testRegisterReader() throws Exception {
        ZapposJson zapposJson = new ZapposJson();
        JsonBeanIntrospector beanIntrospector = new JsonBeanIntrospector();
        JsonReaderCodeGenerator generator = new JsonReaderCodeGenerator(zapposJson, beanIntrospector);

        Class<?> testClass = String.class;
        JsonReaderInvoker readerInvoker = generator.registerReader(testClass);

        // Verify that the reader invoker was correctly generated and stored
        Map<Class<?>, JsonReaderInvoker> readerInvokers = generator.getJSON_READER_INVOKERS();
        assert readerInvokers.containsKey(testClass);
        assert readerInvokers.get(testClass) == readerInvoker;

        // Verify that the generated code can be compiled and executed
        ClassPool classPool = ClassPool.getDefault();
        classPool.importPackage("java.util");
        classPool.importPackage("java.math");
        CtClass jsonCtClass = classPool.get(JsonReader.class.getName());
        CtMethod ctMethod = jsonCtClass.getDeclaredMethod("createObject", new CtClass[] { classPool.get(int.class.getName()), classPool.get(Map.class.getName()) });
        assert ctMethod != null;
        assert ctMethod.getBody() != null;
    }
}
