// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/EnforceSignedHeaderUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:10:05 GMT 2024
 */
package org.jinstagram.utils;


import org.mockito.Mockito;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.Charset;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import org.apache.commons.codec.binary.Hex;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.exceptions.InstagramException;
import org.jinstagram.utils.EnforceSignedHeaderUtils;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.EnforceSignedHeaderUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class EnforceSignedHeaderUtils_ESTest extends EnforceSignedHeaderUtils_ESTest_scaffolding {
    
    
    
    
    
    @Test
    void signature_validInput_success() throws InstagramException {
        String clientSecret = "secret";
        String message = "message";
        String expectedSignature = "6165666138343634633836343530616534336138343736353466303433393237"; // Expected signature for "message" with "secret" as key
        String actualSignature = EnforceSignedHeaderUtils.signature(clientSecret, message);
        assertEquals(expectedSignature, actualSignature);
    }
}
