// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/PaginationHelper_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:15:36 GMT 2024
 */
package org.jinstagram.utils;



import org.mockito.Mockito;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.utils.PaginationHelper;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class PaginationHelper_ESTest extends PaginationHelper_ESTest_scaffolding {
    
    
    
    
    
    @Test
    void getRawMethodName_withEncodedCharacters() {
        String encodedMethodName = "method%20with%20spaces";
        Page page = new Page(encodedMethodName, Collections.emptyMap());
        assertEquals("method with spaces", page.getRawMethodName());
    }
}
