// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;



import com.fasterxml.jackson.databind.type.TypeInfo;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Create a TypeInfo object
        TypeInfo typeInfo = new TypeInfo(String.class);

        // Create a JsonBeanAttribute object
        JsonBeanAttribute detail = new JsonBeanAttribute();
        detail.setName("testAttribute");
        detail.setValue("testValue");

        // Test addAttributeInfo method
        AttributeInfo attrMapping = typeInfo.addAttributeInfo(String.class, detail);

        // Verify the result
        List<AttributeInfo> attrInfos = typeInfo.getAttrInfos();
        assert attrInfos.contains(attrMapping) : "addAttributeInfo method failed";

        // Test if the attribute info is correctly added
        assert attrMapping.getType() == String.class : "Incorrect type added";
        assert attrMapping.getDetail().getName().equals("testAttribute") : "Incorrect detail name added";
        assert attrMapping.getDetail().getValue().equals("testValue") : "Incorrect detail value added";
    }
}
