// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/MediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:28:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;


import com.google.gson.annotations.SerializedName;
import static org.mockito.Mockito.mock;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.entity.users.feed.MediaFeed;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.MediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaFeed_ESTest extends MediaFeed_ESTest_scaffolding {
    
    

    
    
    @Test
    void testToString_withAllFieldsPopulated() {
        List<MediaFeedData> data = new ArrayList<>();
        data.add(new MediaFeedData("123"));
        data.add(new MediaFeedData("456"));
        Meta meta = new Meta(200);
        Pagination pagination = new Pagination("http://example.com/next");

        TagMediaFeed tagMediaFeed = new TagMediaFeed(data, meta, pagination);

        String expected = "TagMediaFeed [data=[MediaFeedData{id='123'}, MediaFeedData{id='456'}], meta=Meta{code=200}, pagination=Pagination{nextUrl='http://example.com/next'}]";
        assertEquals(expected, tagMediaFeed.toString());
    }
}
