// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.awt.geom.Rectangle2D;
import technology.tabula.CohenSutherlandClipping;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    @Test
    public void testSetPositionAndRegion() {
        Point point = new Point(5, 5);
        point.setPositionAndRegion(3, 3);
        assert(point.region == Point.LEFT);

        point.setPositionAndRegion(7, 3);
        assert(point.region == Point.RIGHT);

        point.setPositionAndRegion(5, 3);
        assert(point.region == Point.INSIDE);

        point.setPositionAndRegion(5, 1);
        assert((point.region & Point.BOTTOM) != 0);

        point.setPositionAndRegion(5, 9);
        assert((point.region & Point.TOP) != 0);
    }
}
