// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.awt.geom.Line2D;
import technology.tabula.CohenSutherlandClipping;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    @Test
    public void testClip() {
        // Create a CohenSutherlandClipping object with a clip window
        CohenSutherlandClipping clipper = new CohenSutherlandClipping(new java.awt.Rectangle2D.Float(0, 0, 100, 100));

        // Create a Line2D.Float object
        Line2D.Float line = new Line2D.Float(50, 50, 150, 150);

        // Call the clip method
        boolean result = clipper.clip(line);

        // Assert that the line is completely within the clip window
        assert result : "The line is not completely within the clip window";

        // Assert that the line's coordinates have been updated correctly
        assert line.getX1() == 50 : "The x-coordinate of the first point has not been updated correctly";
        assert line.getY1() == 50 : "The y-coordinate of the first point has not been updated correctly";
        assert line.getX2() == 100 : "The x-coordinate of the second point has not been updated correctly";
        assert line.getY2() == 100 : "The y-coordinate of the second point has not been updated correctly";
    }
}
