// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testGetTextElements() {
        // Create a new Line object
        Line line = new Line();

        // Create some TextChunks
        TextChunk textChunk1 = new TextChunk("Test Chunk 1");
        TextChunk textChunk2 = new TextChunk("Test Chunk 2");

        // Add the TextChunks to the Line
        line.addTextChunk(textChunk1);
        line.addTextChunk(textChunk2);

        // Get the List of TextChunks from the Line
        List<TextChunk> textElements = line.getTextElements();

        // Check that the correct number of TextChunks were returned
        assert(textElements.size() == 2);

        // Check that the correct TextChunks were returned
        assert(textElements.get(0).getText().equals("Test Chunk 1"));
        assert(textElements.get(1).getText().equals("Test Chunk 2"));
    }
}
