// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testSetTextElements() {
        // Create a new Line object
        Line line = new Line();

        // Create a list of TextChunk objects
        List<TextChunk> textChunks = new ArrayList<>();
        TextChunk textChunk1 = new TextChunk("Test Chunk 1");
        TextChunk textChunk2 = new TextChunk("Test Chunk 2");
        textChunks.add(textChunk1);
        textChunks.add(textChunk2);

        // Call the setTextElements method
        line.setTextElements(textChunks);

        // Verify that the textChunks field in the Line object has been updated to reference the new list
        List<TextChunk> updatedTextChunks = line.getTextElements();
        assert(updatedTextChunks.equals(textChunks));
    }
}
