// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testToString() {
        // Create a Line object
        Line line = new Line();

        // Create some TextChunk objects
        TextChunk textChunk1 = new TextChunk("Hello");
        TextChunk textChunk2 = new TextChunk("World");

        // Add the TextChunk objects to the Line object
        line.addTextChunk(textChunk1);
        line.addTextChunk(textChunk2);

        // Call the toString method
        String result = line.toString();

        // Check the result
        // The expected result should be something like: "chunks='Hello', 'World'"
        // Note: The actual result may vary depending on the implementation of the Line and TextChunk classes
        // The important part is that the result contains the text of the TextChunk objects
        assert(result.contains(textChunk1.getText()));
        assert(result.contains(textChunk2.getText()));
    }
}
