// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testRemoveRepeatedCharacters() {
        // Create a Line object with some TextChunks
        Line line = new Line();
        List<TextChunk> textChunks = new ArrayList<>();
        textChunks.add(new TextChunk("aaabbbccc"));
        textChunks.add(new TextChunk("dddeeefff"));
        line.setTextElements(textChunks);

        // Call the removeRepeatedCharacters method
        Line result = Line.removeRepeatedCharacters(line, 'a', 3);

        // Check the result
        assertEquals("bbbccc", result.getTextElements().get(0).getChars());
        assertEquals("ddd", result.getTextElements().get(1).getChars());
    }
}
