// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testAddTextChunk() {
        Line line = new Line();
        TextChunk textChunk1 = new TextChunk("Test1");
        TextChunk textChunk2 = new TextChunk("Test2");

        // Test adding a TextChunk at a valid index
        line.addTextChunk(0, textChunk1);
        List<TextChunk> textChunks = line.getTextElements();
        assert textChunks.get(0).equals(textChunk1);

        // Test adding a TextChunk at an invalid index
        try {
            line.addTextChunk(-1, textChunk2);
            assert false; // If no exception is thrown, the test fails
        } catch (IllegalArgumentException e) {
            assert e.getMessage().equals("i can't be less than 0");
        }

        // Test adding a TextChunk at a valid index that requires adding null elements
        line.addTextChunk(2, textChunk2);
        textChunks = line.getTextElements();
        assert textChunks.size() == 3;
        assert textChunks.get(2).equals(textChunk2);

        // Test adding a TextChunk at a valid index that requires merging with an existing TextChunk
        TextChunk mergedChunk = new TextChunk(textChunk1.getText() + textChunk2.getText());
        line.addTextChunk(1, textChunk2);
        textChunks = line.getTextElements();
        assert textChunks.get(1).equals(mergedChunk);
    }
}
