// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Pair_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:57:41 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import technology.tabula.Pair;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Pair;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Pair_ESTest extends Pair_ESTest_scaffolding {
    @Test
    public void testGetRight() {
        // Given
        R expectedRight = (R) "Expected Right";
        Pair<L, R> pair = new Pair<>(null, expectedRight);

        // When
        R actualRight = pair.getRight();

        // Then
        assertEquals(expectedRight, actualRight);
    }
}
