// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/ProjectionProfile_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import technology.tabula.ProjectionProfile;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {
    @Test
    public void testFilter() {
        float[] data = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f};
        float alpha = 0.5f;
        float[] expected = {1.0f, 1.5f, 2.5f, 3.5f, 4.5f};

        float[] result = ProjectionProfile.filter(data, alpha);

        for (int i = 0; i < data.length; i++) {
            assertEquals(expected[i], result[i], 0.001);
        }
    }
}
