// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/ProjectionProfile_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {
    @Test
    public void testGetAutocorrelation() {
        float[] projection = {10f, 20f, 30f, 40f, 50f};
        float[] expectedAutocorrelation = {0f, 20f, 60f, 120f, 0f};

        float[] autocorrelation = ProjectionProfile.getAutocorrelation(projection);

        for (int i = 0; i < autocorrelation.length; i++) {
            assertEquals(expectedAutocorrelation[i], autocorrelation[i], 0.001);
        }
    }
}
