// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Ruling;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    @Test
    public void testCollapseOrientedRulings() {
        // Create a list of Ruling objects for testing
        List<Ruling> lines = new ArrayList<>();
        lines.add(new Ruling(0f, 0f, 1f, 1f));
        lines.add(new Ruling(0f, 1f, 1f, 2f));
        lines.add(new Ruling(0f, 2f, 1f, 3f));
        lines.add(new Ruling(0f, 3f, 1f, 4f));

        // Call the method to be tested
        List<Ruling> collapsedLines = Ruling.collapseOrientedRulings(lines, 1);

        // Assert that the collapsed lines have the expected size
        assertEquals(2, collapsedLines.size());

        // Assert that the collapsed lines have the expected start and end points
        assertEquals(0f, collapsedLines.get(0).getStart(), 0.001);
        assertEquals(4f, collapsedLines.get(0).getEnd(), 0.001);
        assertEquals(0f, collapsedLines.get(1).getStart(), 0.001);
        assertEquals(4f, collapsedLines.get(1).getEnd(), 0.001);
    }
}
