// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import technology.tabula.Ruling;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    @Test
    public void testFindIntersections() {
        // Create some horizontal and vertical Ruling objects
        Ruling h1 = new Ruling(0, 0, 10, 0);
        Ruling h2 = new Ruling(0, 5, 10, 0);
        Ruling v1 = new Ruling(0, 0, 0, 10);
        Ruling v2 = new Ruling(5, 0, 0, 10);

        // Create lists of horizontal and vertical Ruling objects
        List<Ruling> horizontals = new ArrayList<>();
        horizontals.add(h1);
        horizontals.add(h2);

        List<Ruling> verticals = new ArrayList<>();
        verticals.add(v1);
        verticals.add(v2);

        // Call the findIntersections method
        Map<Point2D, Ruling[]> result = Ruling.findIntersections(horizontals, verticals);

        // Check the result
        assertEquals(2, result.size());

        // Check the first intersection point
        Point2D p1 = new Point2D.Float(5, 0);
        assertTrue(result.containsKey(p1));
        Ruling[] rulings1 = result.get(p1);
        assertEquals(2, rulings1.length);
        assertTrue(rulings1[0].equals(v1) || rulings1[0].equals(v2));
        assertTrue(rulings1[1].equals(h1) || rulings1[1].equals(h2));

        // Check the second intersection point
        Point2D p2 = new Point2D.Float(0, 5);
        assertTrue(result.containsKey(p2));
        Ruling[] rulings2 = result.get(p2);
        assertEquals(2, rulings2.length);
        assertTrue(rulings2[0].equals(v1) || rulings2[0].equals(v2));
        assertTrue(rulings2[1].equals(h1) || rulings2[1].equals(h2));
    }
}
