// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    @Test
    public void testGetRowCount() {
        // Create a new Table instance
        Table table = new Table("TestExtractionMethod");
        
        // Add some RectangularTextContainer instances to the table
        for (int i = 0; i < 5; i++) {
            List<RectangularTextContainer> row = new ArrayList<>();
            for (int j = 0; j < 5; j++) {
                row.add(new RectangularTextContainer(new Rectangle2D.Double(0, 0, 10, 10), "Test"));
           
           }
            table.add(row, i, 0);
        }
        
        // Verify that the getRowCount() method returns the correct number of rows
        int expectedRowCount = 5;
        int actualRowCount = table.getRowCount();
        assert(expectedRowCount == actualRowCount);
    }
}
