// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.List;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    @Test
    public void testGetRows() {
        // Create a new Table instance
        Table table = new Table("TestExtractionMethod");

        // Test if memoizedRows is initially null
        assertNull(table.getMemoizedRows());

        // Call getRows() method
        List<List<RectangularTextContainer>> rows = table.getRows();

        // Test if memoizedRows is not null after calling getRows()
        assertNotNull(table.getMemoizedRows());

        // Test if the returned rows are the same as the memoizedRows
        assertEquals(table.getMemoizedRows(), rows);
    }
}
