// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.TreeMap;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    @Test
    public void testAdd() {
        // Create a new Table instance
        Table table = new Table("Test");

        // Create a RectangularTextContainer instance for testing
        RectangularTextContainer chunk = new RectangularTextContainer();

        // Test add method with valid parameters
        table.add(chunk, 0, 0);

        // Check if the chunk was added to the table correctly
        CellPosition cp = new CellPosition(0, 0);
        RectangularTextContainer addedChunk = table.cells.get(cp);
        assert addedChunk == chunk;

        // Test add method with invalid parameters
        table.add(chunk, -1, -1);

        // Check if the chunk was not added to the table with invalid parameters
        assert table.cells.get(new CellPosition(-1, -1)) == null;
    }
}
