// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testSqueeze() {
        // Create a TextChunk with some TextElements
        TextElement textElement1 = new TextElement(0, 0, 10, 10, "abc");
        TextElement textElement2 = new TextElement(0, 0, 10, 10, "bcb");
        TextElement textElement3 = new TextElement(0, 0, 10, 10, "cbc");
        TextElement textElement4 = new TextElement(0, 0, 10, 10, "bcb");
        TextElement textElement5 = new TextElement(0, 0, 10, 10, "cbc");
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(textElement1);
        textElements.add(textElement2);
        textElements.add(textElement3);
        textElements.add(textElement4);
        textElements.add(textElement5);
        TextChunk textChunk = new TextChunk(textElements);

        // Test squeeze method
        List<TextChunk> result = textChunk.squeeze('b', 3);

        // Check the result
        // In this case, we expect 2 TextChunks: one with "abc" and the other with "cbc"
        // because 'b' appears at least 3 times in a row in the TextElements
        assert result.size() == 2;
        assert result.get(0).getText().equals("abc");
        assert result.get(1).getText().equals("cbc");
    }
}
