// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testHashCode() {
        // Create two TextChunk objects with different textElements
        TextElement textElement1 = new TextElement(0, 0, 10, 10, "Hello");
        TextElement textElement2 = new TextElement(0, 0, 10, 10, "World");
        TextChunk textChunk1 = new TextChunk(textElement1);
        TextChunk textChunk2 = new TextChunk(textElement2);

        // Add the same textElement to both TextChunks
        textChunk1.add(textElement1);
        textChunk2.add(textElement2);

        // Calculate the hashCodes
        int hashCode1 = textChunk1.hashCode();
        int hashCode2 = textChunk2.hashCode();

        // Assert that the hashCodes are different
        assert hashCode1 != hashCode2;
    }
}
