// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testAdd() {
        // Create a TextChunk object
        TextChunk textChunk = new TextChunk(0, 0, 100, 100);

        // Create a list of TextElement objects
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(new TextElement(10, 10, 10, 10, "Test1"));
        textElements.add(new TextElement(20, 20, 10, 10, "Test2"));
        textElements.add(new TextElement(30, 30, 10, 10, "Test3"));

        // Call the add method
        textChunk.add(textElements);

        // Verify that the TextElements were added to the TextChunk
        List<TextElement> addedElements = textChunk.getTextElements();
        assert(addedElements.size() == textElements.size());
        for (int i = 0; i < textElements.size(); i++) {
            assert(addedElements.get(i).equals(textElements.get(i)));
        }
    }
}
