// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testIsLtrDominant() {
        // Create a TextChunk with LTR and RTL text
        TextElement ltrElement = new TextElement(0, 0, 10, 10, "Hello World");
        TextElement rtlElement = new TextElement(0, 0, 10, 10, "مرحبا بالعالم");
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(ltrElement);
        textElements.add(rtlElement);
        TextChunk textChunk = new TextChunk(textElements);

        // Test isLtrDominant() method
        int result = textChunk.isLtrDominant();

        // Assert that the result is positive
        assert(result > 0);
    }
}
