// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testGetText() {
        // Create a TextChunk with some TextElements
        TextElement te1 = new TextElement(0, 0, 10, 10, "Hello");
        TextElement te2 = new TextElement(0, 0, 10, 10, "World");
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(te1);
        textElements.add(te2);
        TextChunk textChunk = new TextChunk(textElements);

        // Test getText() method
        String expected = Normalizer.normalize("HelloWorld", Normalizer.Form.NFKC).trim();
        String actual = textChunk.getText();
        assert(expected.equals(actual));
    }
}
