// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.Arrays;
import java.util.List;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testIsSameChar() {
        // Create a TextChunk with some text
        TextChunk textChunk = new TextChunk("Hello");

        // Test with an array of characters that contains all characters in the text
        Character[] c = {'H', 'e', 'l', 'o'};
        assert(textChunk.isSameChar(c));

        // Test with an array of characters that contains some characters not in the text
        c = new Character[] {'H', 'e', 'l', 'p'};
        assert(!textChunk.isSameChar(c));

        // Test with an array of characters that contains all characters in the text but in a different order
        c = new Character[] {'o', 'l', 'e', 'H'};
        assert(textChunk.isSameChar(c));

        // Test with an array of characters that contains all characters in the text but with upper case
        c = new Character[] {'h', 'E', 'L', 'L', 'O'};
        assert(textChunk.isSameChar(c));

        // Test with an array of characters that contains all characters in the text but with some characters missing
        c = new Character[] {'H', 'e', 'L', 'o'};
        assert(!textChunk.isSameChar(c));
    }
}
