// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testSplitAt() {
        // Create a list of TextElements for testing
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(new TextElement(0, 0, 10, 10, "Test1"));
        textElements.add(new TextElement(0, 10, 10, 10, "Test2"));
        textElements.add(new TextElement(0, 20, 10, 10, "Test3"));
        textElements.add(new TextElement(0, 30, 10, 10, "Test4"));

        // Create a TextChunk with the list of TextElements
        TextChunk textChunk = new TextChunk(textElements);

        // Test splitAt method with valid index
        TextChunk[] splitChunks = textChunk.splitAt(2);
        assert splitChunks.length == 2;
        assert splitChunks[0].getTextElements().size() == 2;
        assert splitChunks[1].getTextElements().size() == 2;

        // Test splitAt method with invalid index
        try {
            textChunk.splitAt(0);
            assert false; // If the method does not throw an exception, it should fail the test
        } catch (IllegalArgumentException e) {
            assert true;
        }

        try {
            textChunk.splitAt(5);
            assert false; // If the method does not throw an exception, it should fail the test
        } catch (IllegalArgumentException e) {
            assert true;
        }
    }
}
