// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testEquals() {
        // Create two TextChunk objects with the same textElements
        TextElement textElement1 = new TextElement(0, 0, 10, 10, "Hello");
        TextElement textElement2 = new TextElement(0, 0, 10, 10, "World");
        ArrayList<TextElement> textElements1 = new ArrayList<>();
        textElements1.add(textElement1);
        ArrayList<TextElement> textElements2 = new ArrayList<>();
        textElements2.add(textElement2);
        TextChunk textChunk1 = new TextChunk(textElements1);
        TextChunk textChunk2 = new TextChunk(textElements2);

        // Test if two TextChunks with the same textElements are equal
        assertTrue(textChunk1.equals(textChunk1));

        // Test if two TextChunks with different textElements are not equal
        assertFalse(textChunk1.equals(textChunk2));

        // Test if TextChunk is equal to itself
        assertTrue(textChunk1.equals(textChunk1));

        // Test if TextChunk is not equal to null
        assertFalse(textChunk1.equals(null));

        // Test if TextChunk is not equal to a different class
        assertFalse(textChunk1.equals(new Object()));
    }
}
