// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthRequest_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:21:21 GMT 2024
 */
package org.jinstagram.auth.model;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OAuthRequest_ESTest extends OAuthRequest_ESTest_scaffolding {
    @Test
    public void testAddOAuthParameter() {
        // Given
        OAuthRequest oAuthRequest = new OAuthRequest(Verbs.GET, "http://example.com");
        String key = "key";
        String value = "value";
        String checkedKey = "checkedKey";
        Map<String, String> expectedOauthParameters = new HashMap<>();
        expectedOauthParameters.put(checkedKey, value);

        // Mock the checkKey method to return the checked key
        OAuthRequest spyOAuthRequest = spy(oAuthRequest);
        doReturn(checkedKey).when(spyOAuthRequest).checkKey(key);

        // When
        spyOAuthRequest.addOAuthParameter(key, value);

        // Then
        assertEquals(expectedOauthParameters, spyOAuthRequest.getOauthParameters());
    }
}
