// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;


import org.mockito.junit.jupiter.MockitoExtension;
import org.scribe.model.OAuthConstants; // Assuming Scribe-Java library is used for OAuth models
import org.scribe.model.OAuthRequest;
import org.scribe.model.Token;
import org.mockito.Mockito;
import com.github.scribejava.core.model.OAuthConstants;
import com.github.scribejava.core.model.OAuthRequest;
import com.github.scribejava.core.model.Token;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.oauth.InstagramService;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {
    




    @Test
    void signRequest_addsAccessTokenAsQueryStringParameter() {
        // Arrange
        String expectedTokenValue = "superSecretAccessToken123";
        // Configure the mock access token to return a specific token string
        when(mockAccessToken.getToken()).thenReturn(expectedTokenValue);

        // Instantiate the InstagramService with its required constructor dependencies.
        // The mockInstagramApi and mockOAuthConfig are passed as they are part of the constructor,
        // even though they are not directly interacted with by the signRequest method itself.
        InstagramService service = new InstagramService(mockInstagramApi, mockOAuthConfig);

        // Act
        // Call the focal method with the mocked access token and OAuth request
        service.signRequest(mockAccessToken, mockRequest);

        // Assert
        // Verify that the addQuerystringParameter method was called on the mockRequest
        // with OAuthConstants.ACCESS_TOKEN as the parameter name and the expected token value.
        verify(mockRequest).addQuerystringParameter(OAuthConstants.ACCESS_TOKEN, expectedTokenValue);

        // Verify that getToken() was called exactly once on the mockAccessToken
        verify(mockAccessToken, times(1)).getToken();

        // Ensure no other interactions occurred with the primary mocks (mockAccessToken, mockRequest)
        // beyond what was explicitly verified.
        verifyNoMoreInteractions(mockAccessToken);
        verifyNoMoreInteractions(mockRequest);

        // Ensure the constructor mocks (mockInstagramApi, mockOAuthConfig) were not interacted with
        // by the signRequest method, confirming its isolated behavior.
        verifyNoInteractions(mockInstagramApi);
        verifyNoInteractions(mockOAuthConfig);
    }
}
