// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/CommentData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:28:38 GMT 2024
 */
package org.jinstagram.entity.comments;
import org.junit.Test;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.FromTagData;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CommentData_ESTest extends CommentData_ESTest_scaffolding {
    @Test
    public void testGetCommentFrom() {
        // Create a new instance of CommentData
        CommentData commentData = new CommentData();

        // Create a mock FromTagData object
        FromTagData mockFromTagData = new FromTagData();
        mockFromTagData.setUsername("testUser");
        mockFromTagData.setId("12345");

        // Set the mock FromTagData object in the CommentData instance
        commentData.setCommentFrom(mockFromTagData);

        // Get the FromTagData object from the CommentData instance
        FromTagData fromTagData = commentData.getCommentFrom();

        // Assert that the username and ID of the FromTagData object match the mock object
        assertEquals("testUser", fromTagData.getUsername());
        assertEquals("12345", fromTagData.getId());
    }
}
