// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;
import org.junit.Test;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.mockito.Mockito;
import org.jinstagram.auth.OAuthRequest;
import org.jinstagram.auth.Response;
import org.jinstagram.auth.OAuthConstants;
import org.jinstagram.auth.OAuthException;
import org.jinstagram.auth.extractor.AccessTokenExtractor;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {
    @Test
    public void testGetAccessToken() {
        // Arrange
        OAuthConfig config = Mockito.mock(OAuthConfig.class);
        InstagramApi api = Mockito.mock(InstagramApi.class);
        Verifier verifier = Mockito.mock(Verifier.class);
        Mockito.when(verifier.getValue()).thenReturn("verifierValue");
        Mockito.when(config.getApiKey()).thenReturn("apiKey");
        Mockito.when(config.getApiSecret()).thenReturn("apiSecret");
        Mockito.when(config.getCallback()).thenReturn("callback");
        Mockito.when(config.hasScope()).thenReturn(false);
        Mockito.when(api.getAccessTokenVerb()).thenReturn("POST");
        Mockito.when(api.getAccessTokenEndpoint()).thenReturn("http://example.com/access_token");
        OAuthRequest request = Mockito.mock(OAuthRequest.class);
        Mockito.when(api.createOAuthRequest(Mockito.anyString())).thenReturn(request);
        Response response = Mockito.mock(Response.class);
        Mockito.when(request.send()).thenReturn(response);
        Mockito.when(response.getBody()).thenReturn("{\"access_token\":\"accessToken\"}");
        AccessTokenExtractor extractor = Mockito.mock(AccessTokenExtractor.class);
        Mockito.when(api.getAccessTokenExtractor()).thenReturn(extractor);
        Mockito.when(extractor.extract(Mockito.anyString())).thenReturn(new Token("accessToken"));

        InstagramService service = new InstagramService(api, config);

        // Act
        Token result = service.getAccessToken(verifier);

        // Assert
        Mockito.verify(request).addBodyParameter(OAuthConstants.CLIENT_ID, "apiKey");
        Mockito.verify(request).addBodyParameter(OAuthConstants.CLIENT_SECRET, "apiSecret");
        Mockito.verify(request).addBodyParameter(OAuthConstants.GRANT_TYPE, "authorization_code");
        Mockito.verify(request).addBodyParameter(OAuthConstants.CODE, "verifierValue");
        Mockito.verify(request).addBodyParameter(OAuthConstants.REDIRECT_URI, "callback");
        Mockito.verify(extractor).extract("{\"access_token\":\"accessToken\"}");
        assert(result.getToken()).equals("accessToken");
    }
}
