// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentsFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:32:11 GMT 2024
 */
package org.jinstagram.entity.comments;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.Meta;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaCommentsFeed_ESTest extends MediaCommentsFeed_ESTest_scaffolding {
    @Test
    public void testToString() {
        // Create a mock Meta object
        Meta mockMeta = new Meta();
        mockMeta.setCode("200");
        mockMeta.setErrorType("");
        mockMeta.setErrorMessage("");

        // Create a mock CommentData object
        CommentData mockCommentData = new CommentData();
        mockCommentData.setId("12345");
        mockCommentData.setText("Test comment");
        mockCommentData.setCreatedTime("2022-01-01T00:00:00+0000");
        mockCommentData.setFrom("Test User");

        // Create a list of mock CommentData objects
        List<CommentData> mockCommentDataList = new ArrayList<>();
        mockCommentDataList.add(mockCommentData);

        // Create a MediaCommentsFeed object
        MediaCommentsFeed mediaCommentsFeed = new MediaCommentsFeed();
        mediaCommentsFeed.setMeta(mockMeta);
        mediaCommentsFeed.setCommentDataList(mockCommentDataList);

        // Test the toString method
        String expected = "MediaCommentsFeed [commentDataList=[CommentData [id=12345, text=Test comment, createdTime=2022-01:00:00+0000, from=Test User]], meta=Meta [code=200, errorType=, errorMessage=]]";
        String actual = mediaCommentsFeed.toString();
        assert(expected.equals(actual));
    }
}
