// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthRequest_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:21:21 GMT 2024
 */
package org.jinstagram.auth.model;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import java.util.HashMap;
import java.util.Map;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OAuthRequest_ESTest extends OAuthRequest_ESTest_scaffolding {
    @Test
    public void testGetOauthParameters() {
        // Create a new OAuthRequest object
        OAuthRequest request = new OAuthRequest(Verbs.GET, "http://example.com");

        // Add some OAuth parameters to the request
        request.addOAuthParameter("key1", "value1");
        request.addOAuthParameter("key2", "value2");

        // Get the OAuth parameters from the request
        Map<String, String> oauthParameters = request.getOauthParameters();

        // Check that the parameters were added correctly
        assertEquals("value1", oauthParameters.get("key1"));
        assertEquals("value2", oauthParameters.get("key2"));
    }
}
