// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/wrapper/ArrayTypeWrapper_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:16:56 GMT 2024
 */
package com.zappos.json.wrapper;
import org.junit.Test;
import com.zappos.json.wrapper.ArrayTypeWrapper;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.wrapper.ArrayTypeWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ArrayTypeWrapper_ESTest extends ArrayTypeWrapper_ESTest_scaffolding {
    @Test
    public void testSetTarget() {
        ArrayTypeWrapper<String> arrayTypeWrapper = new ArrayTypeWrapper<>();
        arrayTypeWrapper.setTarget("Test Target");
        assert arrayTypeWrapper.getTarget().equals("Test Target");
    }
}
