// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/ObjectArray_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {
    @Test
    public void testToArray() {
        // Create an instance of ObjectArray
        ObjectArray objectArray = new ObjectArray();

        // Add some elements to the ObjectArray
        objectArray.add("Element1");
        objectArray.add("Element2");
        objectArray.add("Element3");

        // Call the toArray method
        Object[] resultArray = objectArray.toArray();

        // Create an expected array
        Object[] expectedArray = new Object[3];
        expectedArray[0] = "Element1";
        expectedArray[1] = "Element2";
        expectedArray[2] = "Element3";

        // Assert that the resultArray is equal to the expectedArray
        assert Arrays.equals(resultArray, expectedArray);
    }
}
