// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/ObjectArray_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.util.Arrays;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {
    @Test
    public void testToArray() {
        // Create an ObjectArray instance
        ObjectArray objectArray = new ObjectArray();

        // Add some elements to the ObjectArray
        objectArray.add("Hello");
        objectArray.add("World");

        // Create a new String array and pass it to the toArray method
        String[] stringArray = objectArray.toArray(new String[0]);

        // Assert that the returned array is not null
        assertTrue(stringArray != null);

        // Assert that the returned array has the same size as the ObjectArray
        assertEquals(objectArray.size(), stringArray.length);

        // Assert that the elements in the returned array are the same as the elements in the ObjectArray
        assertEquals(objectArray.get(0), stringArray[0]);
        assertEquals(objectArray.get(1), stringArray[1]);
    }
}
