// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.reflect.Field;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetSecondGenericType() throws NoSuchFieldException {
        // Create a test field with two generic types
        Field testField = Reflections.class.getDeclaredField("getSecondGenericType");
        Class<?>[] genericTypes = new Class<?>[]{List.class, String.class};
        testField.setAccessible(true);
        testField.set(null, genericTypes);

        // Test with a field with two generic types
        Field fieldWithTwoGenericTypes = Reflections.class.getDeclaredField("getSecondGenericType");
        Class<?> secondGenericType = Reflections.getSecondGenericType(fieldWithTwoGenericTypes);
        assert secondGenericType == String.class;

        // Test with a field with only one generic type
        Field fieldWithOneGenericType = Reflections.class.getDeclaredField("getSecondGenericType");
        Class<?> secondGenericTypeOfOneTypeField = Reflections.getSecondGenericType(fieldWithOneGenericType);
        assert secondGenericTypeOfOneTypeField == null;
    }
}
