// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.reflect.Field;
import java.lang.annotation.Annotation;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    

    @Test
    public void testGetFirstGenericType() throws Exception {
        // Test with a field with a generic type
        Field field = Reflections.class.getDeclaredField("focalMethod");
        field.setAccessible(true);
        assertEquals(Integer.class, Reflections.getFirstGenericType(field));

        // Test with a field without a generic type
        Field fieldWithoutGeneric = Reflections.class.getDeclaredField("anotherFocalMethod");
        fieldWithoutGeneric.setAccessible(true);
        assertNull(Reflections.getFirstGenericType(fieldWithoutGeneric));

        // Test with a null field
        assertNull(Reflections.getFirstGenericType(null));
    }
}
