// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.util.Random;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Strings_ESTest extends Strings_ESTest_scaffolding {
    @Test
    public void testRandom() {
        // Test with a fixed seed for reproducibility
        Random RANDOM = new Random(1);

        // Test with a simple character array
        char[] chars = {'a', 'b', 'c', 'd', 'e'};
        int n = 5;
        String expected = "adcbe";
        String actual = Strings.random(n, chars);
        assertEquals(expected, actual);

        // Test with a larger character array
        chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".toCharArray();
        n = 10;
        actual = Strings.random(n, chars);
        assertEquals(n, actual.length());
        for (char c : actual.toCharArray()) {
            assertTrue(new String(chars).contains(String.valueOf(c)));
        }
    }
}
