// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Strings_ESTest extends Strings_ESTest_scaffolding {
    @Test
    public void testIsNumber() {
        // Test with a null string
        assertFalse(Strings.isNumber(null));

        // Test with an empty string
        assertFalse(Strings.isNumber(""));

        // Test with a string that starts with a digit
        assertTrue(Strings.isNumber("123"));

        // Test with a string that starts with a minus sign
        assertTrue(Strings.isNumber("-123"));

        // Test with a string that contains a decimal point
        assertTrue(Strings.isNumber("123.456"));

        // Test with a string that contains more than one decimal point
        assertFalse(Strings.isNumber("123.456.789"));

        // Test with a string that contains a digit after the decimal point
        assertTrue(Strings.isNumber("123.4"));

        // Test with a string that contains a digit after the decimal point and a minus sign
        assertTrue(Strings.isNumber("-123.4"));

        // Test with a string that contains a digit after the decimal point and a minus sign
        assertFalse(Strings.isNumber("123a"));

        // Test with a string that contains a digit after the decimal point and a minus sign
        assertFalse(Strings.isNumber("a123"));

        // Test with a string that contains a digit after the decimal point and a minus sign
        assertFalse(Strings.isNumber("-a123"));

        // Test with a string that contains a digit after the decimal point and a minus sign
        assertFalse(Strings.isNumber("a123a"));
    }
}
