// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import com.zappos.json.util.Strings;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Strings_ESTest extends Strings_ESTest_scaffolding {
    @Test
    public void testFormat() {
        // Test with a pattern and a single argument
        assertEquals("Hello, World", Strings.format("Hello, @", "World"));

        // Test with a pattern and multiple arguments
        assertEquals("Hello, World, John", Strings.format("Hello, @, @", "World", "John"));

        // Test with a pattern and null argument
        assertEquals("Hello, null", Strings.format("Hello, @", null));

        // Test with a pattern and no arguments
        assertEquals("Hello, ", Strings.format("Hello, "));

        // Test with a pattern and more arguments than placeholders
        assertEquals("Hello, World, John, Jane", Strings.format("Hello, @, @", "World", "John", "Jane"));
    }
}
