// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/http/URLUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:48:19 GMT 2024
 */
package org.jinstagram.http;
import com.google.common.base.Preconditions;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.http.URLUtils;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.http.URLUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class URLUtils_ESTest extends URLUtils_ESTest_scaffolding {
    @Test(expected = NullPointerException.class)
    public void testFormURLEncode_nullInput() {
        URLUtils.formURLEncode(null);
    }
}

    @Test
    void formURLEncode_validString_encodesCorrectly() {
        String input = "hello world";
        String expected = "hello+world";
        String actual = URLUtils.formURLEncode(input);
        assertEquals(expected, actual);
    }
}
