// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Point2D;
import technology.tabula.CohenSutherlandClipping;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    

@Test
public void testSetClip() {
    Rectangle2D clipWindow = new Rectangle2D.Double(10, 20, 30, 40);
    CohenSutherlandClipping csc = new CohenSutherlandClipping();
    csc.setClip(clipWindow);

    assert csc.clip(new Line2D.Float(0, 0, 100, 100)); // replace with a line that should be clipped

    assert csc.clip(new Line2D.Float(0, 0, 100, 100)); // replace with a line that should not be clipped
}
}
