// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;





import java.awt.geom.CohenSutherlandClipping;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.awt.geom.Line2D;
import technology.tabula.CohenSutherlandClipping;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    
    
    
    


@Test
    public static void main(String[] args) {
        // Create a clip window
        Rectangle2D clipWindow = new Rectangle2D.Float(0, 0, 100, 100);
        CohenSutherlandClipping clipper = new CohenSutherlandClipping(clipWindow);

        // Test with a line completely inside the clip window
        Line2D.Float line1 = new Line2D.Float(10, 10, 90, 90);
        assert clipper.clip(line1);
        assert line1.getX1() == 10 && line1.getY1() == 10 && line1.getX2() == 90 && line1.getY2() == 90;

        // Test with a line partially inside the clip window
        Line2D.Float line2 = new Line2D.Float(50, 50, 110, 110);
        assert clipper.clip(line2);
        assert line2.getX1() == 60 && line2.getY1() == 60 && line2.getX2() == 100 && line2.getY2() == 100;

        // Test with a line completely outside the clip window
        Line2D.Float line3 = new Line2D.Float(-10, -10, 110, 110);
        assert !clipper.clip(line3);
        assert line3.getX1() == 0 && line3.getY1() == 0 && line3.getX2() == 0 && line3.getY2() == 0;

        // Test with a vertical line outside the clip window
        Line2D.Float line4 = new Line2D.Float(50, -10, 50, 110);
        assert !clipper.clip(line4);
        assert line4.getX1() == 50 && line4.getY1() == 0 && line4.getX2() == 50 && line4.getY2() == 0;

        // Test with a horizontal line outside the clip window
        Line2D.Float line5 = new Line2D.Float(-10, 50, 110, 50);
        assert !clipper.clip(line5);
        assert line5.getX1() == 0 && line5.getY1() == 50 && line5.getX2() == 0 && line5.getY2() == 50;

        System.out.println("All tests passed!");
    }
}
