// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        Line line = new Line();
        TextChunk textChunk1 = new TextChunk();
        TextChunk textChunk2 = new TextChunk();

        // Testing addTextChunk method with empty textChunks list
        line.addTextChunk(textChunk1);
        assert line.textChunks.size() == 1;
        assert line.textChunks.contains(textChunk1);

        // Testing addTextChunk method with non-empty textChunks list
        line.addTextChunk(textChunk2);
        assert line.textChunks.size() == 2;
        assert line.textChunks.contains(textChunk2);

        // Additional assertions or test cases can be added here
        // For instance, you could test the setRect and merge methods
        // by mocking them and asserting their behavior
    }
}
