// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.LinkedList;
import java.util.List;
import technology.tabula.Ruling;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    @Test
    public void testCollapseOrientedRulings() {
        // Create a list of Ruling objects
        List<Ruling> lines = new LinkedList<>();
        lines.add(new Ruling(0, 0, 1, 1));
        lines.add(new Ruling(1, 1, 2, 2));
        lines.add(new Ruling(2, 2, 3, 3));

        // Call the method to be tested
        List<Ruling> collapsedLines = Ruling.collapseOrientedRulings(lines);

        // Assert that the collapsed lines are not null
        assert(collapsedLines != null);

        // Assert that the collapsed lines have the same size as the input lines
        assert(collapsedLines.size() == lines.size());

        // Assert that the collapsed lines are not the same as the input lines
        assert(collapsedLines != lines);
    }
}
