// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    


    
    
    
    
    @Test
    public void testGetRowCount() {

        Table table1 = new Table(ExtractionAlgorithm.ALGORITHM1);
        assertEquals(0, table1.getRowCount()); 
        Table table2 = new Table(ExtractionAlgorithm.ALGORITHM2);
        assertEquals(0, table2.getRowCount()); 
        Table table3 = new Table("Custom Extraction Method");
        assertEquals(0, table3.getRowCount()); 
        Table table4 = new Table(null);
        assertEquals(0, table4.getRowCount()); 
        Table table5 = new Table("");
        assertEquals(0, table5.getRowCount()); 
        Table table6 = new Table(" ");
        assertEquals(0, table6.getRowCount()); 
    }
}
