// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import technology.tabula.Table;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    
    
    


@Test
    public static void main(String[] args) {
        // Create a new Table object with a page number of 5
        Table table = new Table(5);

        // Get the page number from the Table object
        int actualPageNumber = table.getPageNumber();

        // Verify that the actual page number matches the expected page number
        if (actualPageNumber == 5) {
            System.outout("Test passed: getPageNumber() returns the correct page number");
        } else {
            System.out.println("Test failed: getPageNumber() did not return the correct page number");
        }
    }
}
