// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.TreeMap;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Create a new Table instance
        Table table = new Table(new ExtractionAlgorithm() {
            @Override
            public String toString() {
                return "Test Algorithm";
            }
        });

        // Add some cells to the table
        table.cells.put(new CellPosition(0, 0), new RectangularTextContainer("Cell 1"));
        table.cells.put(new CellPosition(1, 1), new RectangularTextContainer("Cell 2"));
        table.cells.put(new CellPosition(2, 2), new RectangularTextContainer("Cell 3"));

        // Test getCell method with existing cells
        assert table.getCell(0, 0).equals(new RectangularTextContainer("Cell 1"));
        assert table.getCell(1, 1).equals(new RectangularTextContainer("Cell 2"));
        assert table.getCell(2, 2).equals(new RectangularTextContainer("Cell 3"));

        // Test getCell method with non-existing cells
        assert table.getCell(3, 3).equals(TextChunk.EMPTY);
        assert table.getCell(4, 4).equals(TextChunk.EMPTY);

        // Test getCell method with negative indices
        assert table.getCell(-1, -1).equals(TextChunk.EMPTY);

        // Test getCell method with out of range indices
        assert table.getCell(Integer.MAX_VALUE, Integer.MAX_VALUE).equals(TextChunk.EMPTY);

        System.out.println("All tests passed!");
    }
}
