// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testGetExtractionMethod() {
        // Test with a known extraction method
        Table table1 = new Table("Known Extraction Method");
        assertEquals("Known Extraction Method", table1.getExtractionMethod());

        // Test with a null extraction method
        Table table2 = new Table(null);
        assertNull(table2.getExtractionMethod());

        // Test with an empty extraction method
        Table table3 = new Table("");
        assertEquals("", table3.getExtractionMethod());

        // Test with an extraction method containing whitespace
        Table table4 = new Table("Extraction Method with Whitespace");
        assertEquals("Extraction Method with Whitespace", table4.getExtractionMethod());

        // Test with an extraction method containing special characters
        Table table5 = new Table("@#$%^&*()");
        assertEquals("@#$%^&*()", table5.getExtractionMethod());

        // Test with an extraction method containing numbers
        Table table6 = new Table("1234567890");
        assertEquals("1234567890", table6.getExtractionMethod());

        // Test with an extraction method containing letters and numbers
        Table table7 = new Table("Extraction123");
        assertEquals("Extraction123", table7.getExtractionMethod());

        // Test with an extraction method containing letters and special characters
        Table table8 = new Table("@#$%^&*()Extraction");
        assertEquals("@#$%^&*()Extraction", table8.getExtractionMethod());

        // Test with an extraction method containing numbers and special characters
        Table table9 = new Table("1234567890@#$%^&*()");
        assertEquals("1234567890@#$%^&*()", table9.getExtractionMethod());

        // Test with an extraction method containing letters, numbers and special characters
        Table table10 = new Table("Extraction123@#$%^&*()");
        assertEquals("Extraction123@#$%^&*()", table10.getExtractionMethod());
    }
}
