// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
Assuming that the TextElement class is defined in a separate file or library, you would need to import it into your file. If the TextElement class is part of the Java standard library, you would need to ensure that the appropriate library is included in your project.



import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    

}


}



@Test
    public static void main(String[] args) {
        // Test with a single TextElement
        TextElement textElement1 = new TextElement(0, 0, 10, 10);
        TextChunk textChunk1 = new TextChunk(textElement1);
        TextChunk[] result1 = textChunk1.splitAt(1);
        assert(Arrays.equals(result1[0].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement1))));
        assert(result1[1].getTextElements().isEmpty());

        // Test with multiple TextElements
        TextElement textElement2 = new TextElement(0, 10, 10, 10);
        TextElement textElement3 = new TextElement(0, 20, 10, 10);
        TextChunk textChunk2 = new TextChunk(Arrays.asList(textElement1, textElement2, textElement3));
        TextChunk[] result2 = textChunk2.splitAt(2);
        assert(Arrays.equals(result2[0].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement1, textElement2))));
        assert(Arrays.equals(result2[1].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement3))));

        // Test with index 1
        TextChunk[] result3 = textChunk2.splitAt(1);
        assert(Arrays.equals(result3[0].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement1))));
        assert(Arrays.equals(result3[1].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement2, textElement3))));

        // Test with index equal to size
        TextChunk[] result4 = textChunk2.splitAt(3);
        assert(Arrays.equals(result4[0].getTextElements(), new ArrayList<TextElement>(Arrays.asList(textElement1, textElement2, textElement3))));
        assert(result4[1].getTextElements().isEmpty());

        // Test with index greater than size
        try {
            textChunk2.splitAt(4);
            assert(false); // If no exception is thrown, this line will not be reached
        } catch (IllegalArgumentException e) {
            assert(true);
        }

        // Test with index less than 1
        try {
            textChunk2.splitAt(0);
            assert(false); // If no exception is thrown, this line will not be reached
        } catch (IllegalArgumentException e) {
            assert(true);
        }
    }
}
