// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;



import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Test with different constructors
        TextChunk textChunk1 = new TextChunk(10, 20, 30, 40);
        TextElement textElement1 = new TextElement(50, 60, 70, 80);
        TextChunk textChunk2 = new TextChunk(textElement1);
        List<TextElement> textElements = Arrays.asList(
                new TextElement(100, 200, 300, 400),
                new TextElement(500, 600, 700, 800)
        );
        TextChunk textChunk3 = new TextChunk(textElements);

        // Test merge method
        TextChunk mergedChunk1 = textChunk1.merge(textChunk2);
        TextChunk mergedChunk2 = textChunk1.merge(textChunk3);

        // Test merge with null
        try {
            textChunk1.merge(null);
        } catch (NullPointerException e) {
            System.out.println("Caught expected exception: " + e.getMessage());
       
	   // Test merge with same object
	   mergedChunk1.merge(mergedChunk1);
	   }
    }
}
