// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;




import java.util.HashMap;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    





@Test
    public static void main(String[] args) {
        // Test with empty TextElements
        TextChunk textChunk1 = new TextChunk(new ArrayList<>());
        try {
            textChunk1.groupByDirectionality(true);
            System.out.println("Test 1: Failed - Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            System.out.println("Test 1: Passed");
        }

        // Test with one TextElement
        TextElement textElement1 = new TextElement("Hello");
        TextChunk textChunk2 = new TextChunk(textElement1);
        TextChunk resultChunk2 = textChunk2.groupByDirectionality(true);
        System.out.println("Test 2: Passed");

        // Test with multiple TextElements
        TextElement textElement2 = new TextElement("World");
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(textElement1);
        textElements.add(textElement2);
        TextChunk textChunk3 = new TextChunk(textElements);
        TextChunk resultChunk3 = textChunk3.groupByDirectionality(true);
        System.out.println("Test 3: Passed");

        // Test with different directionality
        TextElement textElement3 = new TextElement("مرحبا"); // Arabic
        TextElement textElement4 = new TextElement("عليكم"); // Arabic
        textElements.clear();
        textElements.add(textElement3);
        textElements.add(textElement4);
        TextChunk textChunk4 = new TextChunk(textElements);
        TextChunk resultChunk4 = textChunk4.groupByDirectionality(true);
        System.out.println("Test 4: Passed");

        // Test with RTL dominant
        TextChunk textChunk5 = new TextChunk(textElements);
        TextChunk resultChunk5 = textChunk5.groupByDirectionality(false);
        System.out.println("Test 5: Passed");
    }
}
