// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentResponse_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:30:22 GMT 2024
 */
package org.jinstagram.entity.comments;



import com.google.gson.Gson;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.MediaCommentResponse;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaCommentResponse_ESTest extends MediaCommentResponse_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testGetCommentData() {
        // Arrange
        String json = "{\"data\":{\"commenter\":\"John Doe\",\"commentText\":\"This is a test comment.\",\"commentTime\":\"2022-01-01T12:30:00Z\"}}";
        Gson gson = new Gson();
        MediaCommentResponse response = gson.fromJson(json, MediaCommentResponse.class);

        // Act
        CommentData commentData = response.getCommentData();

        // Assert
        assertNotNull(commentData);
        assertEquals("John Doe", commentData.getCommenter());
        assertEquals("This is a test comment.", commentData.getCommentText());
        assertEquals("2022-011T12:30:00Z", commentData.getCommentTime());
    }
}
