// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthRequest_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:21:21 GMT 2024
 */
package org.jinstagram.auth.model;




import org.jinstagram.auth.model.Verbs;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OAuthRequest_ESTest extends OAuthRequest_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testAddOAuthParameter() {
        // Create an instance of OAuthRequest
        OAuthRequest oAuthRequest = new OAuthRequest(Verbs.GET, "http://example.com");

        // Test with valid parameters
        oAuthRequest.addOAuthParameter("oauth_version", "1.0");
        oAuthRequest.addOAuthParameter("oauth_nonce", "1234567890");
        oAuthRequest.addOAuthParameter("oauth_timestamp", "1234567890");
        oAuthRequest.addOAuthParameter("oauth_consumer_key", "consumer_key");
        oAuthRequest.addOAuthParameter("oauth_signature_method", "HMAC-SHA1");
        oAuthRequest.addOAuthParameter("oauth_signature", "signature");
        oAuthRequest.addOAuthParameter("oauth_token", "token");

        // Get the OAuth parameters
        Map<String, String> oauthParameters = oAuthRequest.getOauthParameters();

        // Check if the parameters were added correctly
        assertEquals("1.0", oauthParameters.get("oauth_version"));
        assertEquals("1234567890", oauthParameters.get("oauth_nonce"));
        assertEquals("1234567890", oauthParameters.get("oauth"));
        assertEquals("consumer_key", oauthParameters.get("oauth_consumer_key"));
        assertEquals("HMAC-SHA1", oauthParameters.get("oauth_signature_method"));
        assertEquals("signature", oauthParameters.get("oauth_signature"));
        assertEquals("token", oauthParameters.get("oauth_token"));

        // Test with invalid parameters
        try {
            oAuthRequest.addOAuthParameter("invalid_key", "value");
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // Expected exception
        }
    }
}
