// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/oembed/OembedInformation_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:07:06 GMT 2024
 */
package org.jinstagram.entity.oembed;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.entity.oembed.OembedInformation;
import static org.junit.assertTrue;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OembedInformation_ESTest extends OembedInformation_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testSetVersion() {
        // Create an instance of OembedInformation
        OembedInformation oembedInformation = new OembedInformation();

        // Set a version
        String version = "1.0";
        oembedInformation.setVersion(version);

        // Check if the version is correctly set
        assertEquals(version, oembedInformation.getVersion());
    }
}
