// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Cell_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:42:58 GMT 2024
 */
package technology.tabula;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import technology.tabula.Cell;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Cell_ESTest extends Cell_ESTest_scaffolding {
    



    
    
    @Test
    public void testGetText() {
        // Create a Cell with some TextChunks
        Cell cell = new Cell(0, 0, 10, 10);
        TextChunk tc1 = new TextChunk("Hello", 0, 0, 5, 5);
        TextChunk tc2 = new TextChunk("World", 0, 5, 5, 5);
        cell.getTextElements().add(tc1);
        cell.getTextElements().add(tc2);

        // Test with useLineReturns = true
        String result1 = cell.getText(true);
        assertEquals("Hello\rWorld", result1);

        // Test with useLineReturns = false
        String result2 = cell.getText(false);
        assertEquals("HelloWorld", result2);

        // Test with empty textElements
        cell.getTextElements().clear();
        String result3 = cell.getText(true);
        assertEquals("", result3);
    }
}
