// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;



import java.util.List;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.TreeMap;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Table_ESTest extends Table_ESTest_scaffolding {
    


    
    
    @Test
    public void testAdd() {
        // Create a new Table instance
        Table table = new Table("Test Extraction Method");

        // Create a RectangularTextContainer object for testing
        RectangularTextContainer chunk = new RectangularTextContainer();

        // Test adding a chunk to the table
        table.add(chunk, 0, 0);
        assert(table.cells.size() == 1);
        assert(table.rowCount == 1);
        assert(table.colCount == 1);

        // Test adding a chunk to a specific position in the table
        RectangularTextContainer chunk2 = new RectangularTextContainer();
        table.add(chunk2, 1, 1);
        assert(table.cells.size() == 2);
        assert(table.rowCount == 2);
        assert(table.colCount == 2);

        // Test adding a chunk to an existing position in the table
        RectangularTextContainer chunk3 = new RectangularTextContainer();
        table.add(chunk3, 1, 1);
        assert(table.cells.size() == 2);
        assert(table.rowCount == 2);
        assert(table.colCount == 2);

        // Test adding a chunk to a position that exceeds the current rowCount and colCount
        RectangularTextContainer chunk4 = new RectangularTextContainer();
        table.add(chunk4, 10, 10);
        assert(table.cells.size() == 3);
        assert(table.rowCount == 11);
        assert(table.colCount == 11);

        // Test adding a chunk to a position that is negative
        RectangularTextContainer chunk5 = new RectangularTextContainer();
        table.add(chunk5, -1, -1);
        assert(table.cells.size() == 4);
        assert(table.rowCount == 11);
        assert(table.colCount == 11);
    }
}
