// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;



import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Test with LTR dominant
        TextElement ltrElement1 = new TextElement("Hello", 0, 0, 10, 10);
        TextElement ltrElement2 = new TextElement("World", 0, 10, 10, 10);
        TextChunk ltrChunk = new TextChunk(Arrays.asList(ltrElement1, ltrElement2));
        assert(ltrChunk.isLtrDominant() > 0);

        // Test with RTL dominant
        TextElement rtlElement1 = new TextElement("مرحبا", 0, 0, 10, 10);
        TextElement rtlElement2 = new TextElement("عالم", 0, 10, 10, 10);
        TextChunk rtlChunk = new TextChunk(Arrays.asList(rtlElement1, rtlElement2));
        assert(rtlChunk.isLtrDominant() < 0);

        // Test with equal dominant
        TextElement mixedElement1 = new TextElement("Hello", 0, 0, 10, 10);
        TextElement mixedElement2 = new TextElement("عالم", 0, 10, 10, 10);
        TextChunk mixedChunk = new TextChunk(Arrays.asList(mixedElement1, mixedElement2));
        assert(mixedChunk.isLtrDominant() == 0);

        // Test with mixed dominant
        TextElement mixedElement3 = new TextElement("مرحبا", 0, 0, 10, 10);
        TextElement mixedElement4 = new TextElement("World", 0, 10, 10, 10);
        TextChunk mixedChunk2 = new TextChunk(Arrays.asList(mixedElement3, mixedElement4));
        assert(mixedChunk2.isLtrDominant() > 0);

        System.out.println("All tests passed!");
    }
}
