// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;



import java.util.Arrays;
import java.util.Collections;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Test case 1: Empty textElements list
        TextChunk textChunk1 = new TextChunk(Collections.emptyList());
        System.out.println("Test case 1: " + (textChunk1.getText().equals("") ? "Pass" : "Fail"));

        // Test case 2: textElements list with one TextElement
        TextElement textElement1 = new TextElement(0, 0, 100, 100, "Hello");
        TextChunk textChunk2 = new TextChunk(textElement1);
        System.out.println("Test case 2: " + (textChunk2.getText().equals("Hello") ? "Pass" : "Fail"));

        // Test case 3: textElements list with multiple TextElement objects
        TextElement textElement2 = new TextElement(0, 0, 100, 100, "World");
        List<TextElement> textElements = new ArrayList<>(Arrays.asList(textElement1, textElement2));
        TextChunk textChunk3 = new TextChunk(textElements);
        System.out.println("Test case 3: " + (textChunk3.getText().equals("HelloWorld") ? "Pass" : "Fail"));

        // Test case 4: textElements list with leading and trailing whitespace
        TextElement textElement3 = new TextElement(0, 0, 100, 100, " Leading ");
        TextElement textElement4 = new TextElement(0, 0, 100, 100, " Trailing ");
        textElements = new ArrayList<>(Arrays.asList(textElement3, textElement4));
        TextChunk textChunk4 = new TextChunk(textElements);
        System.out.println("Test case 4: " + (textChunk4.getText().equals("LeadingTrailing") ? "Pass" : "Fail"));

        // Test case 5: textElements list with special characters
        TextElement textElement5 = new TextElement(0, 0, 100, 100, "@#$%^&*");
        textElements = new ArrayList<>(Arrays.asList(textElement5));
        TextChunk textChunk5 = new TextChunk(textElements);
        System.out.println("Test case 5: " + (textChunk5.getText().equals("@#$%^&*") ? "Pass" : "Fail"));
    }
}
