// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    
    



@Test
    public static void main(String[] args) {
        // Test case 1: Testing TextChunk constructor with single TextElement
        TextElement textElement1 = new TextElement(10, 20, 30, 40);
        TextChunk textChunk1 = new TextChunk(textElement1);
        assert textChunk1.getTop() == 10;
        assert textChunk1.getLeft() == 20;
        assert textChunk1.getWidth() == 30;
        assert textChunk1.getHeight() == 40;
        assert textChunk1.getTextElements().size() == 1;

        // Test case 2: Testing TextChunk constructor with multiple TextElements
        TextElement textElement2 = new TextElement(50, 60, 70, 80);
        TextElement textElement3 = new TextElement(90, 100, 110, 120);
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(textElement2);
        textElements.add(textElement3);
        TextChunk textChunk2 = new TextChunk(textElements);
        assert textChunk2.getTop() == 50;
        assert textChunk2.getLeft() == 60;
        assert textChunk2.getWidth() == 70;
        assert textChunk2.getHeight() == 80;
        assert textChunk2.getTextElements().size() == 2;

        // Test case 3: Testing hashCode() method
        assert textChunk1.hashCode() != textChunk2.hashCode();
        TextChunk textChunk3 = new TextChunk(textElement1);
        assert textChunk1.hashCode() == textChunk3.hashCode();
    }
}
