// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;



import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    




@Test
    public static void main(String[] args) {
        // Test with one TextChunk
        TextChunk textChunk1 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk1.add(new TextElement("Hello"));
        List<TextChunk> textChunks1 = Arrays.asList(textChunk1);
        assert !TextChunk.allSameChar(textChunks1);

        // Test with two TextChunks with different first characters
        TextChunk textChunk2 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk2.add(new TextElement("Hello"));
        TextChunk textChunk3 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk3.add(new TextElement("World"));
        List<TextChunk> textChunks2 = Arrays.asList(textChunk2, textChunk3);
        assert !TextChunk.allSameChar(textChunks2);

        // Test with two TextChunks with the same first character
        TextChunk textChunk4 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk4.add(new TextElement("Hello"));
        TextChunk textChunk5 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk5.add(new TextElement("Harry"));
        List<TextChunk> textChunks3 = Arrays.asList(textChunk4, textChunk5);
        assert TextChunk.allSameChar(textChunks3);

        // Test with three TextChunks with the same first character
        TextChunk textChunk6 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk6.add(new TextElement("Hello"));
        TextChunk textChunk7 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk7.add(new TextElement("Harry"));
        TextChunk textChunk8 = new TextChunk(0f, 0f, 10f, 10f);
        textChunk8.add(new TextElement("Heaven"));
        List<TextChunk> textChunks4 = Arrays.asList(textChunk6, textChunk7, textChunk8);
        assert TextChunk.allSameChar(textChunks4);

        // Test with one empty TextChunk
        TextChunk textChunk9 = new TextChunk(0f, 0f, 10f, 10f);
        List<TextChunk> textChunks5 = Arrays.asList(textChunk9);
        assert !TextChunk.allSameChar(textChunks5);
    }
}
