// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    
    



@Test
    public static void main(String[] args) {
        // Test with same reference
        TextChunk textChunk1 = new TextChunk(0f, 0f, 10f, 10f);
        assert textChunk1.equals(textChunk1) : "Same reference test failed";

        // Test with different superclass
        Rectangle rectangle = new Rectangle(0f, 0f, 10f, 10f);
        assert !textChunk1.equals(rectangle) : "Different superclass test failed";

        // Test with different class
        String string = "Test";
        assert !textChunk1.equals(string) : "Different class test failed";

        // Test with null textElements
        TextChunk textChunk2 = new TextChunk(0f, 0f, 10f, 10f);
        assert textChunk1.equals(textChunk2) : "Null textElements test failed";

        // Test with non-null textElements
        List<TextElement> textElements = new ArrayList<>();
        textElements.add(new TextElement(0f, 0f, 10f, 10f));
        textElements.add(new TextElement(0f, 0f, 10f, 10f));
        textChunk2 = new TextChunk(textElements);
        assert textChunk1.equals(textChunk2) : "Non-null textElements test failed";

        // Test with different textElements
        textElements = new ArrayList<>();
        textElements.add(new TextElement(0f, 0f, 10f, 10f));
        textElements.add(new TextElement(1f, 1f, 10f, 10f));
        textChunk2 = new TextChunk(textElements);
        assert !textChunk1.equals(textChunk2) : "Different textElements test failed";

        System.out.println("All tests passed");
    }
}
