// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
        this.y = y;import java.util.List;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    



}



@Test
    public static void main(String[] args) {
        // Test case 1: Adding a single TextElement to TextChunk
        TextElement singleTextElement = new TextElement(10, 20, 30, 40);
        TextChunk textChunk = new TextChunk(singleTextElement);
        List<TextElement> singleElementList = new ArrayList<>();
        singleElementList.add(singleTextElement);
        textChunk.add(singleElementList);
        assert textChunk.size() == 1;

        // Test case 2: Adding multiple TextElements to TextChunk
        TextElement textElement1 = new TextElement(15, 25, 35, 45);
        TextElement textElement2 = new TextElement(20, 30, 40, 50);
        List<TextElement> multipleElementList = new ArrayList<>();
        multipleElementList.add(textElement1);
        multipleElementList.add(textElement2);
        textChunk.add(multipleElementList);
        assert textChunk.size() == 3;

        // Test case 3: Adding an empty List to TextChunk
        List<TextElement> emptyList = new ArrayList<>();
        textChunk.add(emptyList);
        assert textChunk.size() == 3;

        System.out.println("All test cases pass");
    }
}
