// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testGetAttributeInfos() {
        // Create a TypeInfo object with a mock Class object
        TypeInfo typeInfo = new TypeInfo(String.class);

        // Get the list of AttributeInfo objects
        List<AttributeInfo> attrInfos = typeInfo.getAttributeInfos();

        // Assert that the list is not null
        assertNotNull(attrInfos);

        // Assert that the list is empty because we haven't added any AttributeInfo objects yet
        assertTrue(attrInfos.isEmpty());

        // Create a mock AttributeInfo object
        AttributeInfo attrInfo = new AttributeInfo("test");

        // Add the mock AttributeInfo object to the list
        attrInfos.add(attrInfo);

        // Assert that the list now contains one AttributeInfo object
        assertEquals(1, attrInfos.size());

        // Assert that the list contains the mock AttributeInfo object
        assertTrue(attrInfos.contains(attrInfo));
    }
}
