// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;




import com.your.package.PathAndCode; // replace with the actual package of your PathAndCode class
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    

    
    
    
    @Test
    public void testEquals() {
        PathAndCode pathAndCode1 = new PathAndCode("path1", "code1");
        PathAndCode pathAndCode2 = new PathAndCode("path2", "code2");
        PathAndCode pathAndCode3 = new PathAndCode("path1", "code2");
        PathAndCode pathAndCode4 = pathAndCode1;

        // Testing reflexivity
        assertTrue(pathAndCode1.equals(pathAndCode1));

        // Testing symmetry
        assertTrue(pathAndCode1.equals(pathAndCode4));
        assertFalse(pathAndCode1.equals(pathAndCode2));

        // Testing transitivity
        assertFalse(pathAndCode1.equals(pathAndCode3));

        // Testing null
        assertFalse(pathAndCode1.equals(null));

        // Testing different class
        assertFalse(pathAndCode1.equals(new Object()));

        // Testing path comparison
        assertTrue(pathAndCode1.equals(new PathAndCode("path1", "code1")));
        assertFalse(pathAndCode1.equals(new PathAndCode("path1", "code2")));
        assertFalse(pathAndCode1.equals(new PathAndCode("path2", "code1")));
    }
}
