// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/AbstractValueFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:29:33 GMT 2024
 */
package com.zappos.json.format;
import com.zappos.json.format.AbstractValueFormatter;
import com.zappos.json.format.ValueFormatter;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.BigIntegerFormatter;
import com.zappos.json.format.JavaTimeLocalDateFormatter;
import com.zappos.json.format.JavaTimestampFormatter;
import com.zappos.json.format.NoOpValueFormatter;
import java.time.Clock;
import java.time.Period;
import java.time.ZoneOffset;
import java.time.chrono.ChronoLocalDate;
import java.time.chrono.IsoChronology;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class AbstractValueFormatter_ESTest extends AbstractValueFormatter_ESTest_scaffolding {
    
    @Test
    public void testSetJsString() {

        AbstractValueFormatter<Object> formatter = new AbstractValueFormatter<Object>() {

            private String pattern;
            @Override
            public String formatObject(ZapposJson zapposJson, Object object) {
                return null;
            }
            @Override
            public ValueFormatter<Object> setPattern(String pattern) {
                this.pattern = pattern;
                return this;
            }
            @Override
            public String getPattern() {
                return this.pattern;
            }
            @Override
            public String toJsonValue(ZapposJson zapposJson, String value) {
                return null;
            }
        };
        formatter.setJsString(false);
        ZapposJson dummyJson = new ZapposJson();
        assertFalse("JsString should be false after setting to false.", formatter.isJsString());
        formatter.setJsString(true);
        assertTrue("JsString should be true after setting to true.", formatter.isJsString());
        formatter.setJsString(false);
        assertFalse("JsString should be false again after setting to false.", formatter.isJsString());
    }
}
