// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;




import org.mockito.Mockito;
import static org.mockito.Mockito.when;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.oauth.InstagramService;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testGetSignedHeaderInstagram() {
        // Arrange
        OAuthConfig config = Mockito.mock(OAuthConfig.class);
        when(config.getApiSecret()).thenReturn("apiSecret");

        Token accessToken = Mockito.mock(Token.class);
        when(accessToken.getToken()).thenReturn("accessToken");

        InstagramService instagramService = new InstagramService(null, config);

        // Act
        InstagramClient result = instagramService.getSignedHeaderInstagram(accessToken, "127.0.0.1");

        // Assert
        assertNotNull(result);
        assertEquals("accessToken", result.getAccessToken());
        assertEquals("apiSecret", result.getApiSecret());
        assertEquals("127.0.0.1", result.getIpAddress());
    }
}
