// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentResponse_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:30:22 GMT 2024
 */
package org.jinstagram.entity.comments;
import org.junit.Test;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.common.Meta;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaCommentResponse_ESTest extends MediaCommentResponse_ESTest_scaffolding {
    @Test
    public void testGetMeta() {
        // Create a MediaCommentResponse object
        MediaCommentResponse mediaCommentResponse = new MediaCommentResponse();

        // Create a Meta object
        Meta meta = new Meta();

        // Set the Meta object in the MediaCommentResponse
        mediaCommentResponse.setMeta(meta);

        // Get the Meta object from the MediaCommentResponse
        Meta result = mediaCommentResponse.getMeta();

        // Check that the returned Meta object is the same as the one we set
        assert(result == meta);
    }
}
