// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentsFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:32:11 GMT 2024
 */
package org.jinstagram.entity.comments;



import com.google.gson.Gson;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.Meta;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaCommentsFeed_ESTest extends MediaCommentsFeed_ESTest_scaffolding {
    
    
    


@Test
    public static void main(String[] args) {
        // Create a test object
        MediaCommentsFeed mediaCommentsFeed = new MediaCommentsFeed();

        // Create a list of CommentData for testing
        List<CommentData> commentDataList = new ArrayList<>();
        CommentData commentData1 = new CommentData();
        commentData1.setCommentId(1);
        commentData1.setCommentText("Test comment 1");
        commentDataList.add(commentData1);

        CommentData commentData2 = new CommentData();
        commentData2.setCommentId(2);
        commentData2.setCommentText("Test comment 2");
        commentDataList.add(commentData2);

        mediaCommentsFeed.setCommentDataList(commentDataList);

        // Create a Meta object for testing
        Meta meta = new Meta();
        meta.setTotalComments(2);
        meta.setPageNumber(1);
        meta.setPageSize(10);
        mediaCommentsFeed.setMeta(meta);

        // Test the toString method
        System.out.println(mediaCommentsFeed.toString());

        // Test the serialization
        Gson gson = new Gson();
        String json = gson.toJson(mediaCommentsFeed);
        System.out.println(json);

        // Test the deserialization
        MediaCommentsFeed deserializedFeed = gson.fromJson(json, MediaCommentsFeed.class);
        System.out.println(deserializedFeed.toString());
    }
}
