// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:18:36 GMT 2024
 */
package org.jinstagram.auth.model;
import org.junit.Test;
import java.net.Proxy;
import org.jinstagram.auth.model.OAuthConfig;
import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OAuthConfig_ESTest extends OAuthConfig_ESTest_scaffolding {
    @Test
    public void testSetRequestProxy() {
        // Create an instance of OAuthConfig
        OAuthConfig oAuthConfig = new OAuthConfig("apiKey", "apiSecret");

        // Create a Proxy object
        Proxy proxy = new Proxy(Proxy.Type.HTTP, java.net.InetSocketAddress.createUnresolved("proxyHost", 8080));

        // Set the proxy for the OAuthConfig
        oAuthConfig.setRequestProxy(proxy);

        // Verify that the proxy has been set correctly
        assert(oAuthConfig.getRequestProxy().equals(proxy));
    }
}
