// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:18:36 GMT 2024
 */
package org.jinstagram.auth.model;
import org.junit.Test;
import java.net.Proxy;
import org.jinstagram.auth.model.OAuthConfig;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class OAuthConfig_ESTest extends OAuthConfig_ESTest_scaffolding {
    @Test
    public void testGetRequestProxy() {
        // Test with null proxy
        OAuthConfig oAuthConfig = new OAuthConfig("key", "secret");
        assertNull(oAuthConfig.getRequestProxy());

        // Test with non-null proxy
        Proxy proxy = Proxy.NO_PROXY;
        oAuthConfig.setRequestProxy(proxy);
        assertEquals(proxy, oAuthConfig.getRequestProxy());
    }
}
