// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/Token_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:23:21 GMT 2024
 */
package org.jinstagram.auth.model;
import org.junit.Test;
import org.jinstagram.auth.model.Token;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.Token;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Token_ESTest extends Token_ESTest_scaffolding {
    @Test
    public void testGetRawResponse() {
        // Test with non-null rawResponse
        Token token = new Token("token", "secret", "rawResponse");
        assertEquals("rawResponse", token.getRawResponse());

        // Test with null rawResponse
        token = new Token("token", "secret");
        try {
            token.getRawResponse();
        } catch (IllegalStateException e) {
            assertEquals("This token object was not constructed by jInstagramAuthService and does not have a rawResponse", e.getMessage());
        }
    }
}
