// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/InstagramObject_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:52:13 GMT 2024
 */
package org.jinstagram;


import static org.mockito.Mockito.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.instagram.model.InstagramObject;
import java.util.HashMap;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.mockito.Mockito;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.locations.LocationInfo;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramObject_ESTest extends InstagramObject_ESTest_scaffolding {
    
    

    
    
    @Test
    void getRemainingLimitStatus_validHeaders() {
        MockInstagramObject instagramObject = new MockInstagramObject();
        Map<String, String> headers = new HashMap<>();
        headers.put("X-Ratelimit-Remaining", "4999");
        instagramObject.headers = headers;
        assertEquals(4999, instagramObject.getRemainingLimitStatus());
    }
}
