// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/PageDims_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:56:04 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import technology.tabula.PageDims;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.PageDims;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class PageDims_ESTest extends PageDims_ESTest_scaffolding {
    @Test
    public void testGetHeight() {
        // Arrange: Create a PageDims object with a specific height.
        float expectedHeight = 100.0f;
        PageDims pageDims = PageDims.of(10.0f, 20.0f, 50.0f, expectedHeight);

        // Act: Call the getHeight() method.
        float actualHeight = pageDims.getHeight();

        // Assert: Verify that the returned height matches the expected height.
        assertEquals(expectedHeight, actualHeight, 0.001); // Use a delta for float comparison
    }
}
