// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Pair_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:57:41 GMT 2024
 */
package technology.tabula;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import technology.tabula.Pair;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Pair;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Pair_ESTest extends Pair_ESTest_scaffolding {
    
    
    
@Test
    public static void main(String[] args) {
        // Test with valid inputs
        Pair<String, Integer> pair1 = new Pair<>("left", 123);
        System.out.println("Test with valid inputs: " + pair1.getRight());

        // Test with null right element
        Pair<String, String> pair2 = new Pair<>("left", null);
        System.out.println("Test with null right element: " + pair2.getRight());

        // Test with different types
        Pair<Integer, Double> pair3 = new Pair<>(123, 456.789);
        System.out.println("Test with different types: " + pair3.getRight());

        // Test with large numbers
        Pair<String, Long> pair4 = new Pair<>("left", 9876543210L);
        System.out.println("Test with large numbers: " + pair4.getRight());

        // Test with negative numbers
        Pair<String, Integer> pair5 = new Pair<>("left", -123);
        System.out.println("Test with negative numbers: " + pair5.getRight());
    }
}
