// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/InstagramSubscription_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:59:46 GMT 2024
 */
package org.jinstagram.realtime;

import org.mockito.MockedStatic;
import com.github.instagram4j.instagram4j.utils.Preconditions;
import static org.mockito.Mockito.*;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.jinstagram.realtime.InstagramSubscription;
import org.jinstagram.exception.InstagramException;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.jinstagram.realtime.InstagramSubscription;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramSubscription_ESTest extends InstagramSubscription_ESTest_scaffolding {
    

    
    
    
    @Test
    void clientId_validClientId_setsClientIdAndReturnsInstance() {
        InstagramSubscription subscription = new InstagramSubscription();
        String clientId = "testClientId";

        InstagramSubscription result = subscription.clientId(clientId);

        assertNotNull(result);
        assertEquals(subscription, result);
        assertEquals(clientId, subscription.params.get("client_id"));
    }
}
