// original test path: /home/hsc/Documents/Masters/TAES1/ChatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/BasicExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:49:38 GMT 2024
 */
package technology.tabula.extractors;



import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.mockito.Mockito;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Page;
import technology.tabula.Ruling;
import technology.tabula.TextChunk;
import technology.tabula.extractors.BasicExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class BasicExtractionAlgorithm_ESTest extends BasicExtractionAlgorithm_ESTest_scaffolding {
    
    
    
    
    

    @Test
    void extract_validVerticalRulingPositions_extractsTables() {
        // Arrange
        BasicExtractionAlgorithm algorithm = new BasicExtractionAlgorithm();
        Page page = Mockito.mock(Page.class);
        when(page.getTop()).thenReturn(10f);
        when(page.getHeight()).thenReturn(100f);

        List<Float> verticalRulingPositions = new ArrayList<>();
        verticalRulingPositions.add(50f);
        verticalRulingPositions.add(75f);

        // Mock the overloaded extract(Page page) method to return a dummy list of tables.
        BasicExtractionAlgorithm spyAlgorithm = Mockito.spy(algorithm);
        List<Table> expectedTables = new ArrayList<>();
        expectedTables.add(new Table());
        try {
            Mockito.doReturn(expectedTables).when(spyAlgorithm).extract(Mockito.any(Page.class));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        // Act
        List<Table> actualTables = spyAlgorithm.extract(page, verticalRulingPositions);

        // Assert
        assertNotNull(actualTables);
        assertEquals(expectedTables, actualTables);
    }
}
