// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testGetDetail() {
        // Create a JsonBeanAttribute instance for testing
        JsonBeanAttribute detail = new JsonBeanAttribute("name", "type", "defaultValue");

        // Create an AttributeInfo instance with the JsonBeanAttribute
        AttributeInfo attributeInfo = new AttributeInfo(String.class, detail);

        // Test if the getDetail() method returns the correct JsonBeanAttribute
        assertEquals(detail, attributeInfo.getDetail());

        // Test if the getDetail() method returns a new instance of JsonBeanAttribute
        // If getDetail() returns the same instance, it means the field is not encapsulated
        assertNotSame(detail, attributeInfo.getDetail());
    }
}
