// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.concurrent.ConcurrentHashMap;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    


    


    @Test
    public void testDeregisterAll() {
        // Create an instance of JsonReaderCodeGenerator
        JsonReaderCodeGenerator jsonReaderCodeGenerator = new JsonReaderCodeGenerator(null, null);

        // Populate JSON_READER_INVOKERS with some data
        ConcurrentHashMap<Class<?>, JsonReaderInvoker> jsonReaderInvokers = new ConcurrentHashMap<>();
        jsonReaderInvokers.put(String.class, new JsonReaderInvoker(null, null));
        jsonReaderInvokers.put(Integer.class, new JsonReaderInvoker(null, null));
        jsonReaderCodeGenerator.JSON_READER_INVOKERS.putAll(jsonReaderInvokers);

        // Assert that the map has been populated
        assertEquals(2, jsonReaderCodeGenerator.JSON_READER_INVOKERS.size());

        // Call deregisterAll()
        jsonReaderCodeGenerator.deregisterAll();

        // Assert that the map is now empty
        assertEquals(0, jsonReaderCodeGenerator.JSONJSON_READER_INVOKERS.size());
    }
}
