// original test path: /home/mathe/mestrado/merge_and_code_review/projeto/ChatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;



import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import com.zappos.json.util.Reflections;
import java.lang.reflect.Method;
import java.lang.reflect.Field;
import java.lang
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    
    
    
    
    
    @Test
    public void testGetSecondGenericParameterType() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        // Test with a method that has two generic parameters
        Method method = Reflections.class.getDeclaredMethod("getSecondGenericParameterType", Method.class);
        method.setAccessible(true);
        Class<?>[] types = new Class<?>[]{String.class, Integer.class};
        Class<?> result = (Class<?>) method.invoke(null, Method.class.getDeclaredMethod("getName", types));
        assert result == Integer.class;

        // Test with a method that has one generic parameter
        method = Reflections.class.getDeclaredMethod("getSecondGenericParameterType", Method.class);
        method.setAccessible(true);
        types = new Class<?>[]{String.class};
        result = (Class<?>) method.invoke(null, Method.class.getDeclaredMethod("getName", types));
        assert result == null;

        // Test with a method that has no generic parameters
        method = Reflections.class.getDeclaredMethod("getSecondGenericParameterType", Method.class);
        method.setAccessible(true);
        types = new Class<?>[]{};
        result = (Class<?>) method.invoke(null, Method.class.getDeclaredMethod("getName", types));
        assert result == null;
    }
}
